# Project: Project1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o Fuzzy.o InputMembership.o Membership.o OutputMembership.o Rule.o
LINKOBJ  = main.o Fuzzy.o InputMembership.o Membership.o OutputMembership.o Rule.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Fuzzy.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CPP) -c main.c -o main.o $(CXXFLAGS)

Fuzzy.o: Fuzzy.c
	$(CPP) -c Fuzzy.c -o Fuzzy.o $(CXXFLAGS)

InputMembership.o: InputMembership.c
	$(CPP) -c InputMembership.c -o InputMembership.o $(CXXFLAGS)

Membership.o: Membership.c
	$(CPP) -c Membership.c -o Membership.o $(CXXFLAGS)

OutputMembership.o: OutputMembership.c
	$(CPP) -c OutputMembership.c -o OutputMembership.o $(CXXFLAGS)

Rule.o: Rule.c
	$(CPP) -c Rule.c -o Rule.o $(CXXFLAGS)
